/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SofasRouteImport } from './routes/sofas'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FurnituresRouteImport } from './routes/furnitures'
import { Route as CurtainsRouteImport } from './routes/curtains'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ClothesRouteImport } from './routes/clothes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ProductIdIndexRouteImport } from './routes/product/$id/index'

const SofasRoute = SofasRouteImport.update({
  id: '/sofas',
  path: '/sofas',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnituresRoute = FurnituresRouteImport.update({
  id: '/furnitures',
  path: '/furnitures',
  getParentRoute: () => rootRouteImport,
} as any)
const CurtainsRoute = CurtainsRouteImport.update({
  id: '/curtains',
  path: '/curtains',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothesRoute = ClothesRouteImport.update({
  id: '/clothes',
  path: '/clothes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdIndexRoute = ProductIdIndexRouteImport.update({
  id: '/product/$id/',
  path: '/product/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/clothes': typeof ClothesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/curtains': typeof CurtainsRoute
  '/furnitures': typeof FurnituresRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/signup': typeof SignupRoute
  '/sofas': typeof SofasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/product/$id/': typeof ProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/clothes': typeof ClothesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/curtains': typeof CurtainsRoute
  '/furnitures': typeof FurnituresRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/signup': typeof SignupRoute
  '/sofas': typeof SofasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders': typeof OrdersIndexRoute
  '/product/$id': typeof ProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/clothes': typeof ClothesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/curtains': typeof CurtainsRoute
  '/furnitures': typeof FurnituresRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/signup': typeof SignupRoute
  '/sofas': typeof SofasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/product/$id/': typeof ProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/clothes'
    | '/collections'
    | '/contact'
    | '/curtains'
    | '/furnitures'
    | '/login'
    | '/order-success'
    | '/signup'
    | '/sofas'
    | '/admin/dashboard'
    | '/orders/$orderId'
    | '/orders/'
    | '/product/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/clothes'
    | '/collections'
    | '/contact'
    | '/curtains'
    | '/furnitures'
    | '/login'
    | '/order-success'
    | '/signup'
    | '/sofas'
    | '/admin/dashboard'
    | '/orders/$orderId'
    | '/orders'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/clothes'
    | '/collections'
    | '/contact'
    | '/curtains'
    | '/furnitures'
    | '/login'
    | '/order-success'
    | '/signup'
    | '/sofas'
    | '/admin/dashboard'
    | '/orders/$orderId'
    | '/orders/'
    | '/product/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ClothesRoute: typeof ClothesRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  CurtainsRoute: typeof CurtainsRoute
  FurnituresRoute: typeof FurnituresRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  SignupRoute: typeof SignupRoute
  SofasRoute: typeof SofasRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductIdIndexRoute: typeof ProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sofas': {
      id: '/sofas'
      path: '/sofas'
      fullPath: '/sofas'
      preLoaderRoute: typeof SofasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furnitures': {
      id: '/furnitures'
      path: '/furnitures'
      fullPath: '/furnitures'
      preLoaderRoute: typeof FurnituresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curtains': {
      id: '/curtains'
      path: '/curtains'
      fullPath: '/curtains'
      preLoaderRoute: typeof CurtainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothes': {
      id: '/clothes'
      path: '/clothes'
      fullPath: '/clothes'
      preLoaderRoute: typeof ClothesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id/': {
      id: '/product/$id/'
      path: '/product/$id'
      fullPath: '/product/$id/'
      preLoaderRoute: typeof ProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ClothesRoute: ClothesRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  CurtainsRoute: CurtainsRoute,
  FurnituresRoute: FurnituresRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  SignupRoute: SignupRoute,
  SofasRoute: SofasRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductIdIndexRoute: ProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
